// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteCalloutCard(arg1) {
  return window['go']['main']['App']['DeleteCalloutCard'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SendChangeViewRequest(arg1) {
  return window['go']['main']['App']['SendChangeViewRequest'](arg1);
}

export function SendMessage() {
  return window['go']['main']['App']['SendMessage']();
}

export function SendUpdateCallout(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendUpdateCallout'](arg1, arg2, arg3);
}
