// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DeleteCalloutCard(arg1:string):Promise<void>;

export function Greet(arg1:string):Promise<string>;

export function ReturnCalloutUpdateMessage(arg1:main.CalloutUpdateMessage):Promise<main.CalloutUpdateMessage>;

export function ReturnSetupMatch(arg1:main.SetupMatch):Promise<main.SetupMatch>;

export function SendCalloutUpdate(arg1:string,arg2:string):Promise<void>;

export function SendChangeViewRequest(arg1:string):Promise<void>;

export function SendFooterUpdate(arg1:string):Promise<void>;

export function SendMessage():Promise<string>;

export function SendUpdateCallout(arg1:string,arg2:string,arg3:string):Promise<main.SetupMatch>;
